### ISSUE TITLE
Archivierung des Repository

### ISSUE THREAD

**Issue by dersmon** [dainst/hilang#1]
@ahocevar Ich würde dieses Repository mal archivieren, spricht etwas dagegen den Zugriff auf public zu stellen?

**Comment by ahocevar** [comment]
Ok! Auf public stellen ist sehr in meinem Sinn, da spricht überhaupt nichts dagegen. Danke!

**Comment by dersmon** [comment]
Wäre es für dich ok wenn ich dich bei unserem Fork als Collaborator rausschmeiße in dem Zuge? Ich räume gerade etwas auf. ;)

**Comment by ahocevar** [comment]
Ja, ist ok!
